### ISSUE TITLE
option 'g:NERDTreeIndicatorMapCustom' is deprecated

### ISSUE THREAD

**Issue by robmarano** [greekrode/nvim-config#1]
I noticed this evening that the following message was given using this nvim-config:

> [nerdtree-git-status] option 'g:NERDTreeIndicatorMapCustom' is deprecated, please use 'g:NERDTreeGitStatusIndicatorMapCustom'

The NERDTree config portion needs to be updated. Happy to do it, but wanted to get your feedback first.

Thanks,
/rob

**Comment by greekrode** [comment]
Hi @robmarano , sorry I was so late on this.
I never noticed that someone was actually checking out on this repo
I committed a new update on the config file
Thanks!
